

# Dialogue Config
dialogue_conf: conf/benchmark.yaml
dialogue: pandalm_bench
dialogue_dataset: testset

# Server Config
server_conf: conf/server.yaml
server: vllm
model_id: prometheus

# Task Config
task_conf: conf/task.yaml
task: prometheus_eval
task_func: pairwise_single_eval_func

# Eval Config
eval_func: "evaluation"
eval_db_file: data/db_file/eval/{dialogue}_{dialogue_dataset}_{model_id}_{task_func}.sqlite


